"""initial schema

Revision ID: d5589dbaa7b5
Revises:
Create Date: 2026-08-17 18:08:03.898757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d5589dbaa7b5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "monitoring_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pages_attempted", sa.Integer(), nullable=False),
        sa.Column("pages_succeeded", sa.Integer(), nullable=False),
        sa.Column("pages_failed", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("sector", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sites_sector"), "sites", ["sector"], unique=False)
    op.create_index(op.f("ix_sites_slug"), "sites", ["slug"], unique=True)
    op.create_table(
        "tracked_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("page_label", sa.String(length=200), nullable=False),
        sa.Column("crawl_method", sa.String(length=20), nullable=False),
        sa.Column("crawl_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracked_pages_site_id"), "tracked_pages", ["site_id"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_page_id", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_html_path", sa.String(length=500), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("snapshot_metadata", sa.JSON(), nullable=False),
        sa.Column("fetch_duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tracked_page_id"], ["tracked_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snapshots_content_hash"), "snapshots", ["content_hash"], unique=False)
    op.create_index(op.f("ix_snapshots_fetched_at"), "snapshots", ["fetched_at"], unique=False)
    op.create_index(
        op.f("ix_snapshots_tracked_page_id"), "snapshots", ["tracked_page_id"], unique=False
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_page_id", sa.Integer(), nullable=False),
        sa.Column("previous_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("current_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("change_magnitude", sa.Float(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("added_text", sa.Text(), nullable=False),
        sa.Column("removed_text", sa.Text(), nullable=False),
        sa.Column("diff_summary", sa.Text(), nullable=False),
        sa.Column("primary_category", sa.String(length=100), nullable=False),
        sa.Column("signal_score", sa.Float(), nullable=False),
        sa.Column("signal_level", sa.String(length=20), nullable=False),
        sa.Column("is_cosmetic", sa.Boolean(), nullable=False),
        sa.Column("scoring_explanation", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["current_snapshot_id"], ["snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["previous_snapshot_id"], ["snapshots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tracked_page_id"], ["tracked_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_events_detected_at"), "change_events", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_change_events_primary_category"),
        "change_events",
        ["primary_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_events_signal_level"), "change_events", ["signal_level"], unique=False
    )
    op.create_index(
        op.f("ix_change_events_signal_score"), "change_events", ["signal_score"], unique=False
    )
    op.create_index(op.f("ix_change_events_status"), "change_events", ["status"], unique=False)
    op.create_index(
        op.f("ix_change_events_tracked_page_id"), "change_events", ["tracked_page_id"], unique=False
    )
    op.create_table(
        "change_event_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("change_event_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("matched_terms", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["change_categories.id"],
        ),
        sa.ForeignKeyConstraint(["change_event_id"], ["change_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_event_categories_category_id"),
        "change_event_categories",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_event_categories_change_event_id"),
        "change_event_categories",
        ["change_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_change_event_categories_change_event_id"), table_name="change_event_categories"
    )
    op.drop_index(
        op.f("ix_change_event_categories_category_id"), table_name="change_event_categories"
    )
    op.drop_table("change_event_categories")
    op.drop_index(op.f("ix_change_events_tracked_page_id"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_status"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_signal_score"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_signal_level"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_primary_category"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_detected_at"), table_name="change_events")
    op.drop_table("change_events")
    op.drop_index(op.f("ix_snapshots_tracked_page_id"), table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_fetched_at"), table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_content_hash"), table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_tracked_pages_site_id"), table_name="tracked_pages")
    op.drop_table("tracked_pages")
    op.drop_index(op.f("ix_sites_slug"), table_name="sites")
    op.drop_index(op.f("ix_sites_sector"), table_name="sites")
    op.drop_table("sites")
    op.drop_table("monitoring_runs")
    op.drop_table("change_categories")
    # ### end Alembic commands ###
